export const SET_TOP_MESSAGE = 'SET_TOP_MESSAGE'

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'

export const RECEIVE_PERMISSIONS = 'RECEIVE_PERMISSIONS'

export const RECEIVE_CONTEST_LIST = 'RECEIVE_CONTEST_LIST'
export const SORT_CONTEST_LIST = 'SORT_CONTEST_LIST'

export const RECEIVE_CONTEST = 'RECEIVE_CONTEST'

export const RECEIVE_CANDIDATE = 'RECEIVE_CANDIDATE'
